name: "db_unik"

services:
  pg:
    image: postgres:17  
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=unikdb

    volumes:
        - db_data:/var/lib/postgresql/data

volumes:
  db_data: